movieapp/urls.py
from django.urls import path,include
from . import views

app_name='movieapp'
urlpatterns = [
    
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:movie_id>/', views.update, name='update'),
    path('delete/<int:movie_id>/', views.delete, name='delete'),
]

movies/urls.py
from django.contrib import admin
from django.urls import path,include

from movies import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

class Movie(models.Model):
    name=models.CharField(max_length=50)
    dis=models.TextField()
    yr=models.IntegerField()
    img=models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name
    

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','dis','yr','img']

movieapp/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
from django.http import HttpResponse

def index(request):
    movie_list = Movie.objects.all()
    context = {
        'movie_list': movie_list
    }
    return render(request, "index.html", context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request, "details.html",{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        dis=request.POST.get('dis',)
        yr=request.POST.get('yr',)
        img=request.FILES['img']
        movie=Movie(name=name,dis=dis,yr=yr,img=img)
        movie.save()
    return render(request, "add.html")

def update(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, "update.html",{'form':form,'movie':movie})

def delete(request, movie_id):
    if request.method=='POST':
        movie = Movie.objects.get(id=movie_id)
        movie.delete()
        return redirect('/')
    return render(request, "delete.html")
    

templates/add.html
{% extends 'navbar.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Title</title>
</head>
<body>
    <div class='container'>
        <form method='POST' enctype="multipart/form-data" style="border: 2px solid #ddd; padding: 20px;">
            {% csrf_token %}
            <div class="form-group row">
              <label for="staticEmail" class="col-sm-2 col-form-label">Movie Name</label>
              <div class="col-sm-10">
                <input class="form-control" type="text" placeholder="Movie Name" name='name'>
              </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Movie Discription</label>
                <div class="col-sm-10">
                    <textarea class="form-control" rows="3" name='dis'></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="staticEmail" class="col-sm-2 col-form-label">Year</label>
                <div class="col-sm-10">
                  <input class="form-control" type="text" placeholder="Default input" name='yr'>
                </div>
              </div>
            <div class="form-group">
                <label for="exampleFormControlFile1">Example file input</label>
                <input type="file" class="form-control-file" name='img'>
              </div>
              <div class="form-group row">
                <div class="col-sm-10 offset-sm-2">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
          </form>
    </div>
</body>
</html>
{% endblock %}

templates/delete.html
{% extends 'navbar.html' %}
{% block body %}
<div>
  <h2>Delete Movie</h2>
  <p>Are you sure you want to delete the following movie?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
</div>
{% endblock %}

templates/details.html
{% extends 'navbar.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
    <title>Movie Details</title>
</head>
<body>
    <div class="container mt-4">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title">Movie Details</h2>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Movie ID:</strong> {{ movie.id }}</li>
              <li class="list-group-item"><strong>Movie Name:</strong> {{ movie.name }}</li>
              <li class="list-group-item"><strong>Movie Description:</strong> {{ movie.dis }}</li>
              <li class="list-group-item"><strong>Year:</strong> {{ movie.yr }}</li>
              <li class="list-group-item"><strong>Image:</strong> <img src="{{ movie.img.url }}" alt="{{ movie.name }}" class="img-fluid" style="max-height: 200px; width: auto;"></li>
            </ul>
            <div class="mt-3">
              <a href="{% url 'movieapp:update' movie.id %}" class="btn btn-primary">Update</a>
              <a href="{% url 'movieapp:delete' movie.id %}" class="btn btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div>
</body>
</html>
{% endblock %}

templates/index.html
{% extends 'navbar.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Title</title>
</head>
<body>
    <div class='container'>
        <div class="row">
            {% for i in movie_list %}
            <div class="col-md-4 mb-4">
                <div class="card box-shadow" style="width: 18rem; ">
                    <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" style="height:250px;">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <p class="card-text">{{ i.dis }}</p>
                        <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">View More</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>
{% endblock %}

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="add/">Add</a>
                <a class="nav-item nav-link" href="#">Pricing</a>
                <a class="nav-item nav-link disabled" href="#">Disabled</a>
            </div>
        </div>
    </nav>

    <!-- Bootstrap JavaScript and jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    {% block body %}
    {% endblock %}
</body>
</html>

templates/update.html
{% extends 'navbar.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <title>Title</title>
</head>
<body>
    <div class='container'>
        <h3>Update</h3>
        <form method='POST' enctype="multipart/form-data" style="border: 2px solid #ddd; padding: 20px;">
            {% csrf_token %}
            {{form.as_p}}
            <input type='submit'>
</body>
</html>
{% endblock %}